### ISSUE TITLE
JS Primer > Syntax > 1 variables: Has no tests, so cannot pass

### ISSUE THREAD

**Issue by sannylin** [Bloc/workshop-curriculum#112]
https://workshop.bloc.io/exercises/variables-i

![screen shot 2016-09-01 at 11 20 51 am](https://cloud.githubusercontent.com/assets/1298000/18179197/2d6a5bf6-7036-11e6-8d5f-3439dc8a6ebc.png)
![screen shot 2016-09-01 at 11 20 57 am](https://cloud.githubusercontent.com/assets/1298000/18179198/2d6b6000-7036-11e6-983d-225fe20aa4c5.png)

**Comment by barnes7td** [comment]
Tests. Added. Could be part of the bug.
