### ISSUE TITLE
JS Primer > Syntax > 18 Logical Operator: Incorrect information and example

### ISSUE THREAD

**Issue by sannylin** [Bloc/workshop-curriculum#129]
https://workshop.bloc.io/exercises/logical-operators

![screen shot 2016-09-15 at 10 50 41 am](https://cloud.githubusercontent.com/assets/1298000/18560860/436e1bca-7b32-11e6-8130-9b8407d67aca.png)

>(4 > 3) && (9 == '9')    // evaluates to true because both comparisons evaluate to true
>(10 > 7) || (5 === '5')  // evaluates to false because at least one expression is false

`(10 > 7) || (5 === '5')` evaluates to true. We need a different example for `false`.

**Comment by bmneely** [comment]
@sannylin it looks like Blync isn't working for workshop curriculum, so these will need to be manually deployed.
