### ISSUE TITLE
Javascript Primer - Exercise 6 - false positive - kinda

### ISSUE THREAD

**Issue by barnes7td** [Bloc/workshop-curriculum#28]
The exercise is asking for escape characters to be put in the String `\"` , however currently the exercise still passes if a student mixes quote characters. I don't know how to test for this, but it would seem that we would want to fail if they didn't actually use escape characters. 

<img width="1162" alt="js - ex6 - false positive" src="https://cloud.githubusercontent.com/assets/382636/16811032/7b4a1ed8-48f4-11e6-9800-1ff7d0a0504d.png">

**Comment by clln** [comment]
@barnes7td I'll look into this. I think there might be a way to check for that. Though I do know there are a few exercises in which the tests could pass with the student solving the exercise through means other than what's being asked and it's because we can't check for implementation with Mocha. We're pretty limited in that respect.

**Comment by clln** [comment]
@barnes7td I've been working on this this morning and haven't found a solution. The problem is the raw string isn't being tested, just the evaluated string... If you have any suggestions, let me know.

**Comment by barnes7td** [comment]
@clln I will research more on this tonight and see if I can figure something out.

**Comment by clln** [comment]
Thanks @barnes7td ! Much appreciated.

**Comment by barnes7td** [comment]
@clln I have a working code idea. A test that just searches the actual "file" of the solution for characters. Will try to implement a working solution as a PR today. FYI.

**Comment by clln** [comment]
@barnes7td Awesome! If you get that working that would make our testing abilities so much better!

**Comment by barnes7td** [comment]
@clln 

Just to keep you updated. I can test the submission file from the spec file, like I did in my test case locally (that worked), b/c Dre puts both the spec code and the submission code in the same file to run the test. So if I create a test if a certain substring exists in the file, it always will because of that spec that is now in the file that I'm searching (think inception).

I am talking with @choxi if we can set up Dre to separate the specs from the submission. If so, we will be able to have this kind a of testing ability available to us.

**Comment by clln** [comment]
lol, I really liked that explanation. Thanks @barnes7td !

**Comment by barnes7td** [comment]
@clln I think we need to close this one. It's dead.
