### ISSUE TITLE
Workshop While Loop Passes when there is an infinite loop that returns true

### ISSUE THREAD

**Issue by bdougie** [Bloc/workshop-curriculum#84]
My student gave me some interesting looking code that passed the While Loop Checkpoint.

```js
var indexToString = function(array) {
  var newArray = [];
  while (newArray < array) { // always true
    newArray++; // does nothing - we talked about this :)
  }
  return newArray;
};
```

This is not ideal, since he made an error, but wasn't alerted. I can dig into this later, but just want to make others aware this is possible.

**Comment by bdougie** [comment]
What's weird is the exercise did not lock up too.

**Comment by barnes7td** [comment]
@bdougie I don't know for sure, but I think it creates the infinite loop in the Dre API and basically stops the loop and fails with out feedback. I think I have seen similar with a student. We need to reference or add this to the Workshop repo as an issues.

**Comment by mmaxwell** [comment]
To clarify: This is not an infinite loop.

`newArray++` turns newArray into a number, `0` and then increments it, `1`. At which point `newArray < array` actually is `false`.

**Comment by barnes7td** [comment]
@mmaxwell Thanks for the clarification.

I tested what you added and I agree. @bdougie See above.

I think this issue is closed.
